# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quite/qrpc/qrpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15quite/qrpc/qrpc.proto\x12\x04qrpc\"\x17\n\x07Request\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"\x18\n\x08Response\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x32\xee\x03\n\x04QRPC\x12(\n\x05RunUU\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12*\n\x05RunUS\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x30\x01\x12*\n\x05RunSU\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00(\x01\x12,\n\x05RunSS\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00(\x01\x30\x01\x12-\n\nCloneState\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12/\n\x0cRuntimeState\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12+\n\x08\x44ownload\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12)\n\x06Remove\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12\'\n\x04Load\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12)\n\x06Unload\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x12*\n\x07\x43ommand\x12\r.qrpc.Request\x1a\x0e.qrpc.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'quite.qrpc.qrpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=31
  _globals['_REQUEST']._serialized_end=54
  _globals['_RESPONSE']._serialized_start=56
  _globals['_RESPONSE']._serialized_end=80
  _globals['_QRPC']._serialized_start=83
  _globals['_QRPC']._serialized_end=577
# @@protoc_insertion_point(module_scope)
